import { DIFFICULTY, CATEGORY, SUBCATEGORY } from '../util/constants';

export default [
    {
        id: 1,
        text: 'Equip an Abyssal Bludgeon',
        description: 'Equip an Abyssal Bludgeon.',
        difficulty: DIFFICULTY.ELITE,
        category: CATEGORY.BOSSING,
        subcategory: SUBCATEGORY.SIRE,
        skillReqs: [
            { skill: 'Slayer', level: 85 },
            { skill: 'Attack', level: 70 },
            { skill: 'Strength', level: 70 },
        ],
        wiki: '',
    },
    {
        id: 10,
        text: 'Complete the Inferno in 75:00',
        description: 'Complete the Inferno in Mor Ul Rek in 75:00 or less.',
        difficulty: DIFFICULTY.MASTER,
        category: CATEGORY.BOSSING,
        subcategory: SUBCATEGORY.INFERNO,
        skillReqs: [],
        wiki: '',
    },
    {
        id: 2,
        text: 'Complete a Beginner Clue Scroll',
        description: 'Complete a beginner clue scroll by opening a reward casket.',
        difficulty: DIFFICULTY.EASY,
        category: CATEGORY.CLUES,
        subcategory: SUBCATEGORY.BEGINNER,
        skillReqs: [],
        wiki: '',
    },
    {
        id: 3,
        text: 'Complete an Easy Clue Scroll',
        description: 'Complete an easy clue scroll by opening a reward casket.',
        difficulty: DIFFICULTY.EASY,
        category: CATEGORY.CLUES,
        subcategory: SUBCATEGORY.EASY,
        skillReqs: [],
        wiki: '',
    },
    {
        id: 4,
        text: 'Complete a Medium Clue Scroll',
        description: 'Complete a medium clue scroll by opening a reward casket.',
        difficulty: DIFFICULTY.MEDIUM,
        category: CATEGORY.CLUES,
        subcategory: SUBCATEGORY.MEDIUM,
        skillReqs: [],
        wiki: '',
    },
    {
        id: 5,
        text: 'Complete a Hard Clue Scroll',
        description: 'Complete a hard clue scroll by opening a reward casket.',
        difficulty: DIFFICULTY.MEDIUM,
        category: CATEGORY.CLUES,
        subcategory: SUBCATEGORY.HARD,
        skillReqs: [],
        wiki: '',
    },
    {
        id: 6,
        text: 'Complete an Elite Clue Scroll',
        description: 'Complete an elite clue scroll by opening a reward casket.',
        difficulty: DIFFICULTY.HARD,
        category: CATEGORY.CLUES,
        subcategory: SUBCATEGORY.ELITE,
        skillReqs: [],
        wiki: '',
    },
    {
        id: 7,
        text: 'Complete a Master Clue Scroll',
        description: 'Complete a master clue scroll by opening a reward casket.',
        difficulty: DIFFICULTY.HARD,
        category: CATEGORY.CLUES,
        subcategory: SUBCATEGORY.MASTER,
        skillReqs: [],
        wiki: '',
    },
    {
        id: 0,
        text: 'Equip a Full Rune Set',
        description: 'Equip a Rune Platebody, a Rune Full Helm, and either some Rune Platelegs or a Rune Plateskirt.',
        difficulty: DIFFICULTY.MEDIUM,
        category: CATEGORY.COMBAT,
        subcategory: SUBCATEGORY.MELEE,
        skillReqs: [{ skill: 'Defence', level: 40 }],
        wiki: '',
    },
    {
        id: 8,
        text: 'Reach Level 99 Ranged',
        description: 'Reach level 99 in your Ranged skill.',
        difficulty: DIFFICULTY.ELITE,
        category: CATEGORY.COMBAT,
        subcategory: SUBCATEGORY.RANGED,
        skillReqs: [{ skill: 'Ranged', level: 99 }],
        wiki: '',
    },
    {
        id: 9,
        text: "Enter the Wizards' Guild",
        description: "Enter the Wizards' Guild in Yanille.",
        difficulty: DIFFICULTY.MEDIUM,
        category: CATEGORY.COMBAT,
        subcategory: SUBCATEGORY.MAGIC,
        skillReqs: [{ skill: 'Magic', level: 66 }],
        wiki: '',
    },
    {
        id: 11,
        text: 'Complete the Medium Lumbridge & Draynor Diary',
        description: 'Complete all of the medium tasks in the Lumbridge & Draynor Achievement Diary.',
        difficulty: DIFFICULTY.MEDIUM,
        category: CATEGORY.DIARIES,
        subcategory: SUBCATEGORY.MEDIUM,
        skillReqs: [],
        wiki: '',
    },
    {
        id: 12,
        text: 'Equip a Full Void Knight Set',
        description: 'Equip a full set of Void Knight equipment.',
        difficulty: DIFFICULTY.HARD,
        category: CATEGORY.DIARIES,
        subcategory: SUBCATEGORY.PEST_CONTROL,
        skillReqs: [
            { skill: 'Attack', level: 42 },
            { skill: 'Strength', level: 42 },
            { skill: 'Defence', level: 42 },
            { skill: 'Hitpoints', level: 42 },
            { skill: 'Ranged', level: 42 },
            { skill: 'Magic', level: 42 },
            { skill: 'Prayer', level: 22 },
        ],
        wiki: '',
    },
    {
        id: 13,
        text: 'Reach Total Level 500',
        description: 'Reach a Total Level of 500.',
        difficulty: DIFFICULTY.EASY,
        category: CATEGORY.STATS,
        subcategory: SUBCATEGORY.TOTAL_LVL,
        skillReqs: [{ skill: 'Total', level: 500 }],
        wiki: '',
    },
    {
        id: 14,
        text: 'Achieve Your First Level 60',
        description: 'Reach level 60 in any skill.',
        difficulty: DIFFICULTY.HARD,
        category: CATEGORY.STATS,
        subcategory: SUBCATEGORY.MILESTONE_LVL,
        skillReqs: [],
        wiki: '',
    },
    {
        id: 15,
        text: 'Reach Combat Level 100',
        description: 'Reach Combat Level 100.',
        difficulty: DIFFICULTY.HARD,
        category: CATEGORY.STATS,
        subcategory: SUBCATEGORY.COMBAT_LVL,
        skillReqs: [{ skill: 'Combat', level: 100 }],
        wiki: '',
    },
    {
        id: 16,
        text: 'Reach Base Level 80',
        description: 'Reach level 80 in every skill.',
        difficulty: DIFFICULTY.ELITE,
        category: CATEGORY.STATS,
        subcategory: SUBCATEGORY.BASE_LVL,
        skillReqs: [
            { skill: 'Attack', level: 80 },
            { skill: 'Hitpoints', level: 80 },
            { skill: 'Mining', level: 80 },
            { skill: 'Strength', level: 80 },
            { skill: 'Agility', level: 80 },
            { skill: 'Smithing', level: 80 },
            { skill: 'Defence', level: 80 },
            { skill: 'Herblore', level: 80 },
            { skill: 'Fishing', level: 80 },
            { skill: 'Ranged', level: 80 },
            { skill: 'Thieving', level: 80 },
            { skill: 'Cooking', level: 80 },
            { skill: 'Prayer', level: 80 },
            { skill: 'Crafting', level: 80 },
            { skill: 'Firemaking', level: 80 },
            { skill: 'Magic', level: 80 },
            { skill: 'Fletching', level: 80 },
            { skill: 'Woodcutting', level: 80 },
            { skill: 'Runecraft', level: 80 },
            { skill: 'Slayer', level: 80 },
            { skill: 'Farming', level: 80 },
            { skill: 'Construction', level: 80 },
            { skill: 'Hunter', level: 80 },
        ],
        wiki: '',
    },
    {
        id: 17,
        text: "Charge an Amulet of Glory in the Heroes' Guild",
        description: "Charge an amulet of glory at the Fountain of Heroes in the Heroes' Guild.",
        difficulty: DIFFICULTY.MEDIUM,
        category: CATEGORY.QUESTS,
        subcategory: SUBCATEGORY.EXPERIENCED_QUEST,
        skillReqs: [
            { skill: 'Quest', level: 55 },
            { skill: 'Cooking', level: 53 },
            { skill: 'Fishing', level: 53 },
            { skill: 'Herblore', level: 25 },
            { skill: 'Mining', level: 50 },
            { skill: 'Crafting', level: 31 },
            { skill: 'Woodcutting', level: 36 },
        ],
        wiki: '',
    },
    {
        id: 18,
        text: "Enter the Myths' Guild",
        description: "Enter the Myths' Guild.",
        difficulty: DIFFICULTY.HARD,
        category: CATEGORY.QUESTS,
        subcategory: SUBCATEGORY.GRANDMASTER_QUEST,
        skillReqs: [
            { skill: 'Quest', level: 200 },
            { skill: 'Combat', level: 85 },
            { skill: 'Cooking', level: 53 },
            { skill: 'Fishing', level: 53 },
            { skill: 'Herblore', level: 45 },
            { skill: 'Mining', level: 68 },
            { skill: 'Crafting', level: 62 },
            { skill: 'Woodcutting', level: 55 },
            { skill: 'Magic', level: 75 },
            { skill: 'Smithing', level: 70 },
            { skill: 'Agility', level: 60 },
            { skill: 'Thieving', level: 60 },
            { skill: 'Construction', level: 50 },
            { skill: 'Hitpoints', level: 50 },
            { skill: 'Prayer', level: 42 },
            { skill: 'Strength', level: 50 },
            { skill: 'Ranged', level: 30 },
            { skill: 'Defence', level: 40 },
            { skill: 'Firemaking', level: 49 },
            { skill: 'Slayer', level: 18 },
        ],
        wiki: '',
    },
    {
        id: 19,
        text: 'Complete the Theatre of Blood With No Deaths',
        description: 'Complete the Theatre of Blood without any party member dying.',
        difficulty: DIFFICULTY.ELITE,
        category: CATEGORY.RAIDS,
        subcategory: SUBCATEGORY.TOB,
        skillReqs: [],
        wiki: '',
    },
    {
        id: 20,
        text: 'Complete Room 8 of Pyramid Plunder',
        description: 'Search the Golden Chest in Room 8 of Pyramid Plunder in Sophanem.',
        difficulty: DIFFICULTY.ELITE,
        category: CATEGORY.SKILLING,
        subcategory: SUBCATEGORY.THIEVING,
        skillReqs: [{ skill: 'Thieving', level: 91 }],
        wiki: '',
    },
    {
        id: 21,
        text: 'Unlock a Gate in Taverley Dungeon',
        description: 'Unlock a gate in Taverley Dungeon using the dusty key.',
        difficulty: DIFFICULTY.EASY,
        category: CATEGORY.OTHER,
        subcategory: SUBCATEGORY.LOCATIONS,
        skillReqs: [],
        wiki: '',
    },
    // {
    //     id: ,
    //     text: '',
    //     description: '',
    //     difficulty: DIFFICULTY.,
    //     category: CATEGORY.,
    //     subcategory: SUBCATEGORY.,
    //     skillReqs: [
    //         { skill: '', level:  },
    //     ],
    //     wiki: ''
    // },
];
