/* ID MAPPING */

// since we're using task name as a hash, if task name string changes we'll
// have to manually map it to the old hash to keep user's progress state
const ID_OVERRIDES = {
    '750 Wintertodt Kills': 1354,
    "Achieve 100% Shades of Mort'Ton Sanctity": 499,
    'Achieve Your First Level 10': 500,
    'Achieve Your First Level 20': 578,
    'Achieve Your First Level 30': 579,
    'Achieve Your First Level 40': 498,
    'Achieve Your First Level 5': 580,
    'Achieve Your First Level 50': 672,
    'Achieve Your First Level 60': 673,
    'Achieve Your First Level 70': 674,
    'Achieve Your First Level 95': 497,
    'Ascent of Arceuus': 1345,
    'Bank at Mount Quidamortem': 976,
    'Brimstail Rune Essence Mine teleport': 1266,
    'Build a Demonic Throne': 922,
    'Build a Gilded Portal Nexus': 616,
    'Build a Mahogany Portal': 539,
    'Build a Room in Your Player Owned House': 595,
    'Build a Waka Canoe': 697,
    'Build an Achievement Gallery': 617,
    'Build an Obelisk': 623,
    'Burn 100 Willow Logs': 700,
    'Burn 100 Yew Logs': 574,
    'Burn Some Coloured Logs': 517,
    'Burn Some Food': 701,
    'Burn Some Magic Logs': 544,
    'Burn Some Normal Logs': 545,
    'Burn Some Oak Logs': 564,
    'Bury Some Bones': 1063,
    'Bury Some Lava Dragon Bones': 650,
    'Bury Some Wyvern or Dragon Bones': 1130,
    'Buy a Snapdragon From Pirate Jackie the Fruit': 1298,
    'Buy Something From Trader Crewmembers': 645,
    'Cast a Blast Spell': 714,
    'Cast a Surge Spell': 713,
    'Cast Blood Barrage': 1204,
    'Cast Bones to Peaches': 1075,
    'Cast Degrime Spell Full Clean': 921,
    'Cast Fertile Soil': 1076,
    'Cast Full Sinister Offering': 647,
    'Cast High Level Alchemy': 562,
    'Cast Ice Barrage': 1220,
    'Cast Ice Blitz': 1219,
    'Cast Ice Burst': 1202,
    'Cast Kourend Castle Teleport': 903,
    'Cast Moonclan Teleport': 1227,
    'Cast Resurrect Superior Ghost': 1074,
    'Cast Saradomin Strike': 1222,
    'Cast Shadow Barrage': 1221,
    'Cast Spellbook Swap': 1081,
    'Catch 100 Dark Crabs': 1140,
    'Catch 100 Karambwans': 611,
    'Catch 100 Lobsters': 694,
    'Catch 100 Shark': 1297,
    'Catch 200 Implings in Puro-Puro': 1197,
    'Catch 30 Orange Salamanders': 1273,
    'Catch 50 Implings in Puro-Puro': 1009,
    'Catch 50 Red Chinchompas in Kandarin': 613,
    'Catch 50 Salmon': 612,
    'Catch 50 Swordfish': 547,
    'Catch a Baby Impling': 1082,
    'Catch a Black Chinchompa': 1065,
    'Catch a Black Salamander': 628,
    'Catch a Butterfly': 967,
    'Catch a Crimson Swift in the Feldip Hills': 1416,
    'Catch a Crystal Impling': 702,
    'Catch a Herbiboar 500 Times': 533,
    'Catch a Herring': 1122,
    'Catch a Lucky Impling Bare-Handed': 1010,
    'Catch a Monkfish': 986,
    'Catch a Red Salamander': 1131,
    'Catch a Salmon on Karamja': 532,
    'Catch a Shrimp': 907,
    'Catch a Snowy Knight': 1342,
    'Catch a Swamp Lizard in Morytania': 627,
    'Catch a Swamp Lizard or Salamander': 534,
    'Catch an Anchovy': 845,
    "Charge an Amulet of Glory in the Heroes' Guild": 1406,
    'Charter a Ship From Prifddinas to Port Tyras': 1216,
    'Check a grown Cactus': 1141,
    'Check a grown Calquat Tree': 1415,
    'Check a grown Dragonfruit Tree in Catherby': 592,
    'Check a grown Fruit Tree': 1299,
    'Check a grown Magic Tree in Lumbridge': 1300,
    'Check a grown Mahogany Tree': 680,
    'Check a grown Palm Tree': 1408,
    'Check a grown Papaya Tree in Lletya': 989,
    'Check a grown Papaya Tree in the Gnome Stronghold': 1217,
    'Check a grown Redwood Tree': 528,
    'Check Your Slayer Task': 593,
    'Chop 100 Willow Logs': 682,
    'Chop a Magic Log at the Forsaken Tower': 1281,
    'Chop a Sulliuscep Cap': 513,
    'Chop Some Logs': 594,
    'Chop Some Logs With a Rune Axe': 514,
    'Chop Some Logs With a Steel Axe': 705,
    'Clean 100 Grimy Dwarf Weed': 631,
    'Clean a Grimy Avantoe': 551,
    'CM Chambers of Xeric in Target Time': 943,
    'Complete 100 Farming Contracts': 689,
    'Complete 25 Farming Contracts': 703,
    'Complete 250 Laps of a Rooftop Agility Course': 1278,
    'Complete 50 Farming Contracts': 629,
    'Complete 50 Laps of a Rooftop Agility Course': 688,
    'Complete 75 Farming Contracts': 570,
    'Complete a Beginner Clue Scroll': 968,
    'Complete a Fishing Trawler Game': 852,
    'Complete a Game of Intermediate Pest Control': 836,
    'Complete a Game of Novice Pest Control': 870,
    'Complete a Game of Veteran Pest Control': 655,
    'Complete a Hard Clue Scroll': 1369,
    'Complete a Hard Temple Trek': 718,
    'Complete a Master Clue Scroll': 654,
    'Complete a Medium Clue Scroll': 1351,
    'Complete a Medium Temple Trek': 849,
    'Complete A Porcine of Interest': 550,
    'Complete a Rooftop Agility Course': 1294,
    "Complete a Soul's Bane": 1353,
    'Complete A Taste of Hope': 1274,
    'Complete a Volcanic Mine Game': 571,
    'Complete an Easy Clue Scroll': 1332,
    'Complete an Easy Temple Trek': 717,
    'Complete an Elite Clue Scroll': 1291,
    'Complete Death to the Dorgeshuun': 1292,
    'Complete Demon Slayer': 1000,
    'Complete Elemental Workshop II': 1226,
    'Complete Fishing Contest': 1338,
    'Complete Floor 1 of the Hallowed Sepulchre': 1339,
    'Complete Floor 2 of the Hallowed Sepulchre': 1356,
    'Complete Floor 3 of the Hallowed Sepulchre': 1357,
    'Complete Floor 5 of the Hallowed Sepulchre': 1261,
    "Complete Gertrude's Cat": 1352,
    'Complete Haunted Mine': 973,
    "Complete Monk's Friend": 920,
    "Complete Olaf's Quest": 1262,
    'Complete Romeo & Juliet': 1170,
    'Complete Room 1 of Pyramid Plunder': 1171,
    'Complete Room 2 of Pyramid Plunder': 1185,
    'Complete Room 3 of Pyramid Plunder': 1186,
    'Complete Room 4 of Pyramid Plunder': 1187,
    'Complete Room 5 of Pyramid Plunder': 1209,
    'Complete Room 6 of Pyramid Plunder': 1210,
    'Complete Room 8 of Pyramid Plunder 50 Times': 919,
    'Complete Royal Trouble': 1256,
    'Complete Rune Mysteries': 975,
    'Complete Sea Slug': 1208,
    'Complete Shadow of the Storm': 1260,
    'Complete Sheep Shearer': 1370,
    'Complete Sins of the Father': 1205,
    'Complete Spirits of the Elid': 1174,
    'Complete the Ardougne Agility Course': 983,
    'Complete the Barbarian Outpost Agility Course': 1340,
    'Complete the Corrupted Gauntlet in 8:30': 1250,
    'Complete the Draynor Agility Course': 979,
    'Complete the Easy Ardougne Diary': 1177,
    'Complete the Easy Desert Diary': 833,
    'Complete the Easy Falador Diary': 898,
    'Complete the Easy Fremennik Diary': 980,
    'Complete the Easy Kandarin Diary': 1126,
    'Complete the Easy Karamja Diary': 1255,
    'Complete the Easy Lumbridge & Draynor Diary': 1331,
    'Complete the Easy Morytania Diary': 1252,
    'Complete the Easy Varrock Diary': 577,
    'Complete the Easy Western Provinces Diary': 1053,
    'Complete the Elite Wilderness Diary': 837,
    'Complete the Fight Caves in 35:00': 1421,
    'Complete the Gauntlet in 5:00': 1427,
    'Complete the Gauntlet in 8:00': 966,
    'Complete the Gnome Stronghold Agility Course': 1184,
    'Complete the Hallowed Sepulchre in 6:30': 1358,
    'Complete the Hallowed Sepulchre in 8:00': 1018,
    'Complete the Hard Ardougne Diary': 1224,
    'Complete the Hard Desert Diary': 866,
    'Complete the Hard Falador Diary': 942,
    'Complete the Hard Fremennik Diary': 1022,
    'Complete the Hard Kandarin Diary': 1150,
    'Complete the Hard Karamja Diary': 1308,
    'Complete the Hard Lumbridge & Draynor Diary': 1368,
    'Complete the Hard Morytania Diary': 1296,
    'Complete the Hard Varrock Diary': 740,
    'Complete the Hard Western Provinces Diary': 1093,
    'Complete the Inferno in 75:00': 496,
    'Complete the Leagues Tutorial': 1290,
    'Complete The Lost Tribe': 1003,
    'Complete the Medium Ardougne Diary': 1203,
    'Complete the Medium Desert Diary': 847,
    'Complete the Medium Falador Diary': 917,
    'Complete the Medium Fremennik Diary': 1006,
    'Complete the Medium Kandarin Diary': 1134,
    'Complete the Medium Karamja Diary': 1288,
    'Complete the Medium Lumbridge & Draynor Diary': 1350,
    'Complete the Medium Morytania Diary': 1282,
    'Complete the Medium Varrock Diary': 670,
    'Complete the Medium Western Provinces Diary': 1077,
    'Complete the Medium Wilderness Diary': 1268,
    'Complete the Natural History Quiz': 1001,
    'Complete the Observatory Quest': 906,
    'Complete the Penguin Agility Course': 1417,
    'Complete the Prifddinas Agility Course': 1418,
    'Complete the Prifddinas Agility Course in 1:10': 923,
    'Complete the Rellekka Agility Course': 1008,
    'Complete the Theatre of Blood With No Deaths': 1341,
    'Complete the Werewolf Agility Course': 1064,
    'Complete the Wilderness Agility Course': 918,
    'Complete Throne of Miscellania': 974,
    'Complete Tower of Life': 1264,
    'Complete Vampyre Slayer': 1343,
    'Convert 2,000 Daeyalt Shards Into Essence': 1138,
    'Cook 100 Karambwans': 597,
    'Cook 100 Lobsters': 683,
    'Cook a Dark Crab': 1399,
    'Cook a Rabbit in Tirannwn': 516,
    'Cook a Shrimp': 608,
    'Craft 100 Unpowered Orbs': 619,
    'Craft 200 Essence Into Runes': 698,
    'Craft 2500 Essence Into Runes': 693,
    'Craft 30 Blue Dragonhide Bodies': 620,
    'Craft 4 Runes With 1 Essence': 905,
    'Craft 50 Astral Runes': 1279,
    'Craft 50 Cosmic Runes': 1409,
    'Craft 50 Death Runes': 856,
    'Craft 50 Law Runes': 1132,
    'Craft 50 Nature Runes': 1251,
    'Craft 50 Water Runes': 840,
    'Craft a Chaos Rune using a Chaos Core': 692,
    'Craft a Dragonstone Amulet': 1175,
    'Craft a Ghorrock Teleport Tablet': 1196,
    'Craft a Lava Rune at the Fire Altar': 531,
    'Craft a Leather Body': 1420,
    'Craft a Piece of Crystal Armour': 610,
    'Craft a Ruby Amulet': 1344,
    'Craft a Rune Using Daeyalt Essence': 1326,
    'Craft a Toxic Trident': 1083,
    'Craft an Air Battlestaff in the Wilderness': 827,
    'Craft an Air Rune': 609,
    'Craft an Emerald Ring': 1432,
    'Craft an Onyx Amulet': 621,
    'Craft Any Combination Rune': 542,
    'Create a Catherby Teleport Tablet': 603,
    'Create an Amulet of Blood Fury': 1401,
    'Cut a Cactus in the Kharidian Desert': 530,
    'Cut a Sapphire': 690,
    'Defeat 1500 Demonic Gorillas': 691,
    'Defeat 20 Superior Slayer Creatures': 846,
    'Defeat 750 Demonic Gorillas': 910,
    'Defeat a Basilisk Knight': 832,
    'Defeat a Black Demon in Asgarnia': 995,
    'Defeat a Bloodveld in Kandarin': 1412,
    'Defeat a Bloodveld in Tirannwn': 831,
    'Defeat a Blue Dragon in Asgarnia': 1014,
    'Defeat a Cave Kraken': 1051,
    'Defeat a Chaos Dwarf in the Wilderness': 895,
    'Defeat a Cockatrice in the Fremennik Province': 1194,
    'Defeat a Crocodile': 913,
    'Defeat a Dagannoth in the Fremennik Province': 1424,
    'Defeat a Dark Beast in Tirannwn': 1012,
    'Defeat a Dust Devil in the Kharidian Desert': 996,
    'Defeat a Fire Giant in Kandarin': 1050,
    'Defeat a Fire Giant in the Wilderness': 1347,
    'Defeat a Fiyr Shade': 1283,
    'Defeat a Fossil Island Wyvern': 1362,
    'Defeat a Gargoyle in Morytania': 1330,
    'Defeat a Ghast': 567,
    'Defeat a Goblin': 1125,
    'Defeat a Greater Demon on Karamja': 1052,
    'Defeat a Green Dragon in the Wilderness': 568,
    'Defeat a Hydra': 916,
    'Defeat a Jelly in the Fremennik Province': 1200,
    'Defeat a Kalphite Guardian': 911,
    'Defeat a Kurask in the Fremennik Province': 1413,
    'Defeat a Kurask in Tirannwn': 1049,
    'Defeat a Lava Dragon in the Wilderness': 652,
    'Defeat a Lesser Demon': 990,
    'Defeat a Mithril Dragon': 569,
    'Defeat a Moss Giant': 1403,
    'Defeat a Moss Giant in Tirannwn': 1431,
    'Defeat a Nechryael in Tirannwn': 896,
    'Defeat a Pyrefiend in the Fremennik Province': 894,
    'Defeat a Rock Crab in the Fremennik Province': 1303,
    'Defeat a Rune Dragon': 1199,
    'Defeat a Scarab Mage': 843,
    'Defeat a Skeletal Wyvern': 687,
    'Defeat a Smoke Devil': 1133,
    'Defeat a Steel Dragon on Karamja': 607,
    'Defeat a Superior Slayer Creature': 970,
    'Defeat a Tortoise With Riders in Kandarin': 830,
    'Defeat a Troll in Asgarnia': 897,
    'Defeat a Troll in the Fremennik Province': 915,
    'Defeat a Turoth in the Fremennik Province': 1123,
    'Defeat a TzHaar': 1348,
    'Defeat a Vyrewatch Sentinel': 1285,
    'Defeat a Wall Beast': 1402,
    'Defeat a Waterfiend in Tirannwn': 1328,
    'Defeat a Werewolf in Morytania': 1363,
    'Defeat an Abyssal Demon in Morytania': 653,
    'Defeat an Al Kharid Warrior': 1307,
    'Defeat an Ancient Wyvern': 1411,
    'Defeat Any God Wars Dungeon Boss 500 Times': 1286,
    'Defeat Bryophyta': 1085,
    'Defeat Cerberus Before She Summons Souls': 864,
    'Defeat Each Dagannoth King 650 Times': 862,
    'Defeat General Graardor': 861,
    "Defeat K'ril Tsutsaroth": 863,
    'Defeat Nex 500 Times': 1284,
    'Defeat Obor': 1329,
    "Defeat Phosani's Nightmare": 1067,
    'Defeat Scorpia': 850,
    'Defeat Some Animated Rune Armour': 1306,
    'Defeat the Abyssal Sire 500 Times': 1069,
    'Defeat the Chaos Elemental': 1068,
    'Defeat the Corporeal Beast 500 Times': 1066,
    'Defeat the Crazy Archaeologist': 930,
    'Defeat the Dagannoth Kings Without Leaving': 842,
    'Defeat the Giant Mole 750 Times': 1367,
    'Defeat the Grotesque Guardians': 1364,
    'Defeat the Kalphite Queen 500 Times': 1087,
    'Defeat the Kraken Boss 750 Times': 1253,
    "Defeat The Nightmare or Phosani's Nightmare 750 times": 1002,
    'Defeat the Thermonuclear Smoke Devil': 1084,
    'Defeat Venenatis': 1086,
    "Defeat Vet'ion": 927,
    'Defeat Vorkath in 1:00': 929,
    'Defeat Vorkath in 2:00': 1422,
    'Defeat Zalcano 500 Times': 1423,
    'Defeat Zulrah in 0:54': 1426,
    'Defeat Zulrah in 1:30': 899,
    'Depths of Despair': 681,
    'Dig Up Some Magic Roots': 1271,
    'Drink a Poison Chalice': 553,
    'Drink a Strength Potion': 1263,
    'Drink From the Tears of Guthix': 527,
    'Earn Some Slayer Points': 575,
    'Enhance a Trident of the Seas': 1269,
    'Enter Level 3 of the Chasm of Fire': 1207,
    'Enter Sophanem': 1129,
    'Enter the Brimhaven Dungeon': 1275,
    "Enter the Cooks' Guild": 839,
    'Enter the Crafting Guild': 1079,
    "Enter the Farming Guild's Mid Tier": 987,
    'Enter the Fishing Guild': 1183,
    'Enter the Kalphite Lair': 1017,
    "Enter the Myths' Guild": 993,
    'Enter the Ranging Guild': 1135,
    'Enter the Taverly Dungeon': 848,
    "Enter the Warriors' Guild": 1059,
    'Enter the Wilderness God Wars Dungeon': 1058,
    'Enter the Wilderness Resource Area': 994,
    'Enter the Woodcutting Guild': 576,
    'Enter your Player Owned House': 1257,
    'Equip 500 Black Chinchompas': 931,
    'Equip a Bonecrusher necklace': 1072,
    'Equip a Brimstone Ring': 912,
    'Equip a Brine Sabre': 712,
    "Equip a Craw's Bow": 1428,
    'Equip a Crystal Crown': 1430,
    'Equip a Crystal Halberd': 1429,
    'Equip a Crystal Shield': 1425,
    "Equip a Dinh's Bulwark": 1287,
    'Equip a Dorgeshuun Crossbow': 1223,
    'Equip a Dragon 2H Sword': 1089,
    'Equip a Dragon Crossbow': 860,
    'Equip a Dragon Hunter Lance': 1088,
    'Equip a Dragon Platebody or Dragon Kiteshield': 991,
    'Equip a Dragon Warhammer': 708,
    'Equip a Dust Battlestaff': 1070,
    'Equip a Fedora': 1013,
    'Equip a Fish Sack': 638,
    'Equip a Full Adamant Set': 1011,
    'Equip a Full Bandos Armour Set': 709,
    'Equip a Full Black Dragonhide Set': 641,
    'Equip a Full Dragon Set': 733,
    'Equip a Full Gilded or Trimmed Wizard Set': 734,
    'Equip a Full Gilded Set': 737,
    'Equip a Full God Dragonhide Set': 736,
    'Equip a Full God Rune Set': 853,
    'Equip a Full Graceful Outfit': 640,
    'Equip a Full Justiciar Set': 558,
    'Equip a Full Mithril Set': 1142,
    'Equip a Full Obsidian Armour Set': 855,
    'Equip a Full Prospector Outfit': 642,
    'Equip a Full Red Dragonhide Set': 941,
    'Equip a Full Rockshell Armour Set': 854,
    'Equip a Full Rogue Outfit': 639,
    "Equip a Full Set of Zealot's Robes": 939,
    'Equip a Full Skeletal Armour Set': 940,
    'Equip a Full Spined Armour Set': 1137,
    'Equip a Full Tai Bwo Wannai Villager Set': 735,
    'Equip a Full Vestment Set': 867,
    'Equip a Ghrazi Rapier': 1073,
    'Equip a Golden Tench': 1366,
    'Equip a Granite Hammer or Granite Ring': 668,
    'Equip a Granite Shield': 624,
    'Equip a Heavy Casket': 914,
    'Equip a Helm of Neitiznot': 1304,
    'Equip a Hill Giant Club': 1005,
    'Equip a Kruk Jr. Monkey Backpack': 671,
    'Equip a Lava Battlestaff': 938,
    'Equip a Leaf-Bladed Battleaxe': 669,
    "Equip a Mage's Book": 710,
    'Equip a Malediction Ward': 1021,
    'Equip a Maniacal Monkey Backpack': 560,
    'Equip a Maple Shortbow': 977,
    'Equip a Master Wand': 1136,
    'Equip a Mist Battlestaff': 557,
    'Equip a Mithril Weapon': 978,
    'Equip a Monkey Backpack': 936,
    'Equip a Nightmare Staff With an Orb': 865,
    'Equip a Pearl Fishing Rod': 648,
    'Equip a Piece of a Mystic Set': 1349,
    'Equip a Piece of the Bandos Armour Set': 1094,
    'Equip a Piece of the Golden Prospector set': 1225,
    'Equip a Prince Awowogei Monkey Back': 1151,
    'Equip a Ring of the Gods': 711,
    'Equip a Rune Crossbow': 637,
    'Equip a Rune Weapon': 1355,
    'Equip a Scythe of Vitur': 937,
    'Equip a Seercull': 933,
    'Equip a Spectral or Arcane Spirit Shield': 526,
    'Equip a Spiny Helmet': 985,
    'Equip a Staff of the Dead': 559,
    "Equip a Thammaron's Sceptre": 1146,
    'Equip a Toktz-Ket-Xil': 1148,
    'Equip a Toktz-Xil-Ak': 1149,
    'Equip a Treasonous Ring': 1015,
    'Equip a Trident of the Seas': 667,
    'Equip a Tyrannical Ring': 1147,
    "Equip a Viggora's Chainmace": 932,
    'Equip a Willow Shield': 563,
    'Equip a Wizard Robe and Hat': 643,
    'Equip an Abyssal Whip': 636,
    'Equip an Ancient Wyvern Shield': 934,
    'Equip an Armadyl Crossbow': 928,
    'Equip an Elder Maul': 644,
    'Equip an Elemental Battlestaff or Mystic Staff': 561,
    'Equip an Elysian Spirit Shield': 1090,
    'Equip an Expert Dragon Archer Chompy Hat': 998,
    "Equip an Inquisitor's Mace": 1145,
    'Equip an Odium Ward': 1020,
    'Equip an Ogre Expert Chompy Hat': 1004,
    'Equip an Ogre Forester Chompy Hat': 738,
    'Equip any Ancestral piece': 1365,
    'Equip Boots of Brimstone': 1305,
    'Equip Ferocious Gloves': 626,
    'Equip full Graahk, Larupia or Kyatt': 1144,
    'Equip Some Dragon Platelegs or a Dragon Plateskirt': 1270,
    'Equip Some Fancy Boots or Fighting Boots': 844,
    'Equip Some Guardian Boots': 1289,
    'Equip Some Primordial, Pegasian or Eternal Boots': 739,
    "Equip Xeric's Talisman": 596,
    'Ferment 100 Jugs of Wine': 727,
    'Fill 10 Beginner Clue Collection Log Slots': 731,
    'Fill 10 Elite Clue Collection Log Slots': 730,
    'Fill 15 Hard Clue Collection Log Slots': 728,
    'Fill 20 Easy Clue Collection Log Slots': 729,
    'Fill 25 Master Clue Collection Log Slots': 666,
    'Fill 3 Elite Clue Collection Log Slots': 665,
    'Fill 40 Medium Clue Collection Log Slots': 662,
    'Fill 5 Beginner Clue Collection Log Slots': 663,
    'Fill 5 Easy Clue Collection Log Slots': 732,
    'Fill 5 Master Clue Collection Log Slots': 664,
    'Fill 50 Easy Clue Collection Log Slots': 591,
    'Fill a Bucket With Supercompost': 1127,
    'Fill a Crate With Bananas': 699,
    'Fill a Giant Pouch': 696,
    'Fill a Hard S.T.A.S.H. Unit': 622,
    'Fill a Large Pouch': 618,
    'Fill Every Beginner Clue Collection Log Slot': 1152,
    'Find a Gout Tuber': 1405,
    'Find Every Memoriam Crystal': 524,
    'Fletch 150 Iron Arrows': 981,
    'Fletch 50 Maple Longbow (u) in Kandarin': 685,
    'Fletch a Magic Shortbow': 686,
    'Fletch a Rune Crossbow': 602,
    'Fletch a Willow Shortbow': 523,
    'Fletch an Oak Shortbow': 522,
    'Fletch Some Arrow Shafts': 604,
    'Friend of House Shayzien': 1265,
    'Fully Unlock the Mycelium Transportation System': 658,
    'Gain 10 Unique Items From Beginner Clues': 659,
    'Gain 10 Unique Items From Easy Clues': 725,
    'Gain 10 Unique Items From Elite Clues': 726,
    'Gain 10 Unique Items From Master Clues': 660,
    'Gain 10 Unique Items From Medium Clues': 724,
    'Gain 25 Unique Items From Master Clues': 723,
    'Gain 25 Unique Items From Medium Clues': 721,
    'Gain 35 Unique Items From Beginner Clues': 722,
    'Gain 35 Unique Items From Easy Clues': 661,
    'Gain 50 Unique Items From Hard Clues': 572,
    'Gain a Unique Item From a Beginner Clue': 657,
    'Gain a Unique Item From a Hard Clue': 720,
    'Gain a Unique Item From a Master Clue': 656,
    'Gain a Unique Item From a Medium Clue': 573,
    'Gain a Unique Item From an Easy Clue': 719,
    'Get Stung By Bees': 1178,
    'Go Through the Al Kharid Gate': 924,
    'Harvest a Snapdragon in Weiss': 590,
    'Harvest an Irit Leaf': 841,
    'Harvest Any Herb at the Troll Stronghold': 1400,
    'Harvest Some Sweetcorn in Prifddinas': 1228,
    'Have Zahur Make 1,000 Unfinished Potions At Once': 1092,
    'Inferior Demonbane Demon Kill': 869,
    'Kourend and Kebos Medium Diary Tasks': 625,
    'Light a Bullseye Lantern': 546,
    'Light a Torch': 543,
    'Locate a Runecrafting Altar With a Talisman': 1346,
    'Loot a Barrows Chest': 1214,
    'Make 20 Magic Potions': 857,
    'Make 20 Ranging Potions': 858,
    'Make 20 Stamina Potions': 630,
    'Make 30 Prayer Potions': 632,
    'Make a 4 dose potion': 1193,
    'Make a Combat Potion': 598,
    'Make a Pineapple Pizza': 704,
    'Make a Super Combat Potion': 552,
    'Metamorphise the Olmlet': 1198,
    'Mine 30 Chunks of Granite': 684,
    'Mine 50 Adamantite Ore': 599,
    'Mine a Runite Ore Fragment': 519,
    'Mine some Copper Ore': 600,
    'Mine some Ore With a Rune Pickaxe': 520,
    'Mine Some Runite Ore in the Wilderness': 1201,
    'Move Your House to Pollnivneach': 1410,
    'Move Your House to Prifddinas': 904,
    'Move Your House to Rellekka': 828,
    'Move Your House to Taverley': 988,
    'Move Your House to Yanille': 838,
    'Obtain 25 Million Woodcutting XP': 588,
    'Obtain 800 Coins From Coin Pouches At Once': 515,
    'Obtain a Casket from Fishing': 601,
    'Obtain a Crystal Tool Seed': 521,
    'Obtain a Gem While Mining': 549,
    'Obtain a Mark of Grace': 1335,
    'Obtain Adamantite Ore at the Blast Mine': 1071,
    'Obtain an Ecumenical Key': 1360,
    'Open 250 Grubby Chests': 508,
    'Open a Gold Chest': 1078,
    'Open an Ornate Lockbox': 1080,
    "Open One of Larran's Chests": 851,
    'Open the Crystal Chest': 1433,
    'Open the Enhanced Crystal Chest': 495,
    'Open the Leagues Menu': 1054,
    'Order a Drink at the Old Nite': 635,
    'Perform a Special Attack': 1259,
    'Pet a Stray Dog in Varrock': 1334,
    "Pick a Autumn Sq'irk": 1128,
    'Pick a Pineapple on Karamja': 1188,
    "Pick a Spring Sq'irk": 1211,
    "Pick a Summer Sq'irk": 1172,
    'Pick Wheat in Catherby': 1191,
    'Pickpocket a Bandit in the Bandit Camp': 1277,
    'Pickpocket a Bullseye Lantern From a Cave Goblin': 507,
    'Pickpocket a Diamond From a TzHaar': 587,
    'Pickpocket a Guard': 1248,
    'Pickpocket a H.A.M. Member': 1007,
    'Pickpocket a Hero': 982,
    'Pickpocket a Master Farmer': 1213,
    'Pickpocket a Menaphite Thug 50 Times': 589,
    'Pickpocket a Ranarr Seed': 1276,
    'Pickpocket a Varrock Guard': 1361,
    'Pickpocket a Vyre 50 Times': 1419,
    'Plant 100 Logavano Seeds': 511,
    'Plant Seeds in an Allotment Patch': 1206,
    'Pray at the Elidinis Statuette': 1056,
    'Pray at the Southern Chaos Temple': 1057,
    'Pray at the Western Chaos Temple': 512,
    'Purchase a Celestial ring': 538,
    'Purchase a Player Owned House': 1359,
    'Queen of Thieves': 510,
    'Rake a Farming Patch': 651,
    'Reach a Prayer Bonus of 15': 716,
    'Reach a Prayer Bonus of 30': 505,
    'Reach Base Level 10': 506,
    'Reach Base Level 20': 584,
    'Reach Base Level 30': 585,
    'Reach Base Level 40': 504,
    'Reach Base Level 5': 586,
    'Reach Base Level 50': 677,
    'Reach Base Level 60': 678,
    'Reach Base Level 95': 554,
    'Reach Combat Level 10': 706,
    'Reach Combat Level 100': 707,
    'Reach Combat Level 126': 555,
    'Reach Combat Level 25': 633,
    'Reach Combat Level 50': 634,
    'Reach Combat Level 75': 1019,
    'Reach Level 99 Woodcutting': 501,
    'Reach Total Level 100': 582,
    'Reach Total Level 1000': 583,
    'Reach Total Level 1250': 675,
    'Reach Total Level 1500': 676,
    'Reach Total Level 2277': 502,
    'Reach Total Level 250': 503,
    'Reach Total Level 500': 581,
    'Receive a Konar Slayer Task': 525,
    'Receive a Slayer Task': 1124,
    'Receive a Slayer Task From Duradel': 1327,
    'Receive a Slayer Task From Nieve or Steve': 829,
    'Receive a Slayer Task From Turael or Spria': 1254,
    'Receive All Chambers of Xeric Uniques': 1121,
    'Recolour a piece of Ancestral': 565,
    'Restore 5 Prayer Points at an Altar': 715,
    'Sacrifice a Fire Cape to Access the Inferno': 1047,
    'Sacrifice Some Bones at the Chaos Temple': 1062,
    'Serve 20 Stews in the Mess Hall': 992,
    'Set Up a Dwarf Cannon': 1295,
    'Setup a Magic Bird House': 1272,
    'Setup a Yew Bird House': 606,
    'Slay an Abyssal Demon': 535,
    'Smelt a Bronze Bar': 695,
    'Smelt a Runite Bar': 615,
    'Smelt a Steel Bar': 536,
    'Smelt an Iron Bar': 1215,
    'Smith 1000 Adamant Dart Tips': 1192,
    'Smith 1000 Rune Dart Tips': 537,
    'Smith a Dragonfire Shield': 614,
    'Smith a Steel Platebody': 548,
    'Solo CM Chambers of Xeric in Target Time': 529,
    'Steal 500 Artefacts': 509,
    'Steal a Chocolate Slice': 859,
    'Steal a Golovanova Fruit Top': 679,
    'Steal From a Gem Stall': 1249,
    'Steal Some Silk': 518,
    'Successfully Cook 5 Pieces of Food': 566,
    'Superhuman Strength and Improved Reflexes': 1143,
    'Survive a Hit From TzTok-Jad Without Prayer': 893,
    'Switch to the Lunar Spellbook': 1182,
    'Take a Carpet Ride from Pollnivneach to Sophanem': 1139,
    'Take a Shortcut Across the Shilo Village River': 1302,
    'Tale Of The Righteous': 1407,
    "Teleport to Xeric's Honour": 646,
    'Trade 1,000 Agility Arena Tickets for XP': 1091,
    'Transform into Uri': 925,
    'Trap a Sabre-Toothed Kyatt': 984,
    'Travel Between Your Spirit Trees': 1258,
    'Travel to Molch Island': 540,
    'Turn in 10 Library Books': 1190,
    'Turn in 100 Library Books': 868,
    "Turn in 100 Summer Sq'irkjuices to Osman": 1212,
    'Turn in 500 Library Books': 1195,
    'Turn in a Pyramid Top to Simon Templeton': 1173,
    "Turn in a Winter Sq'irkjuice to Osman": 834,
    'Unlock All Catacombs Entrances': 605,
    'Unlock Bigger and Badder': 908,
    'Unlock Free Use of the Blast Furnace': 1293,
    'Use a Digsite Pendant to Teleport to Fossil Island': 1267,
    'Use a Fairy Ring': 1055,
    'Use a Lever to Teleport to Edgeville': 1414,
    'Use an Elven Teleport Crystal': 1280,
    'Use Enriched Bones on the Strange Machine': 909,
    'Use Some Icy Basalt to Teleport to Weiss': 1048,
    'Use the Abyss': 1060,
    'Use the Bank at the Mage Arena': 1404,
    'Use the Bank in Lletya': 1180,
    'Use the Bank in Nardah': 900,
    'Use the Bank on Jatizso': 902,
    'Use the Bank on Lunar Isle': 901,
    'Use the Bank on Neitiznot': 997,
    'Use the Explore Emote': 1016,
    'Use the Piety Prayer': 649,
    'Use the Protect from Melee Prayer': 1247,
    'Use the Range in Lumbridge Castle': 935,
    'Use the Special Attack of a Dragon Axe': 926,
    'Use Your Portal Nexus to Teleport to Weiss': 556,
    "Visit Death's Domain": 1061,
    'Visit Ferox Enclave': 1336,
    'Visit Harmony Island': 1337,
    "Visit Mos Le'Harmless": 1333,
    'Visit Port Phasmatys': 541,
    'Visit the Rune Essence Mine': 972,
    'Visit the Tree Gnome Stronghold': 971,
    'Visit the Tree Gnome Village': 999,
};

function mapTaskToId(taskName) {
    if (ID_OVERRIDES[taskName]) {
        return ID_OVERRIDES[taskName];
    }

    // copypasta from https://stackoverflow.com/questions/6122571/simple-non-secure-hash-function-for-javascript
    var hash = 0;
    for (var i = 0; i < taskName.length; i++) {
        var char = taskName.charCodeAt(i);
        hash = (hash << 5) - hash + char;
        hash |= 0; // Convert to 32bit integer
        hash = hash >>> 0; // Force to positive
    }
    return hash;
}

/* CATEGORY MAPPING */

function mapTaskToCategories(task) {
    // TODO
    return {};
}

exports.toId = mapTaskToId;
exports.toCategories = mapTaskToCategories;
